<<<<<<< Updated upstream
# Generated by Django 5.2.9 on 2026-01-13 08:03
=======
# Generated by Django 5.2.9 on 2026-01-22 22:02
>>>>>>> Stashed changes

import django.db.models.deletion
import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< Updated upstream
        ('polizas', '0001_initial'),
        ('usuarios', '0001_initial'),
=======
        ('polizas', '0003_poliza_pdf_file_deducible'),
>>>>>>> Stashed changes
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('descripcion_evento', models.CharField(max_length=255)),
                ('dias_transcurridos', models.IntegerField()),
                ('estado', models.IntegerField()),
                ('fecha_ocurrencia', models.DateField()),
                ('fecha_reporte', models.DateField()),
                ('ubicacion', models.CharField(max_length=255)),
                ('tipo_evento', models.CharField(max_length=50)),
                ('bien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polizas.bienasegurado')),
            ],
        ),
        migrations.CreateModel(
            name='Danio',
            fields=[
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='siniestros.evento')),
                ('area_asignada', models.CharField(max_length=100)),
                ('tecnico_asignado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hurto',
            fields=[
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='siniestros.evento')),
                ('ubicacion_ultima_vista', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Robo',
            fields=[
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='siniestros.evento')),
                ('valor_perdido', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Siniestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< Updated upstream
                ('numero_siniestro', models.CharField(max_length=20, unique=True, verbose_name='Número de Siniestro')),
                ('fecha_ocurrencia', models.DateField(verbose_name='Fecha de Ocurrencia')),
                ('fecha_reporte', models.DateField(auto_now_add=True, verbose_name='Fecha de Reporte')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('monto_reclamado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Reclamado')),
                ('monto_aprobado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto Aprobado')),
                ('estado', django_fsm.FSMField(choices=[('reportado', 'Reportado'), ('en_revision', 'En Revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('pagado', 'Pagado')], default='reportado', max_length=50, verbose_name='Estado')),
                ('cobertura_valida', models.IntegerField()),
                ('fecha_apertura', models.DateField()),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('tiempo', models.IntegerField()),
                ('tipo_bien', models.CharField(max_length=50)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('numero_serie', models.CharField(max_length=100)),
                ('asesor_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.asesorutpl')),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='siniestros.broker')),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siniestros', to='polizas.poliza', verbose_name='Póliza')),
                ('reclamante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siniestros', to='usuarios.usuario', verbose_name='Reclamante')),
            ],
            options={
                'verbose_name': 'Siniestro',
                'verbose_name_plural': 'Siniestros',
=======
                ('numero_siniestro', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Número de Siniestro')),
                ('reclamante_nombre', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('reclamante_email', models.EmailField(max_length=254, verbose_name='Email del Reclamante')),
                ('reclamante_telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('tipo_evento', models.CharField(choices=[('danio', 'Daño'), ('robo', 'Robo'), ('hurto', 'Hurto'), ('incendio', 'Incendio'), ('inundacion', 'Inundación'), ('terremoto', 'Terremoto'), ('otro', 'Otro')], max_length=50, verbose_name='Tipo de Evento')),
                ('ubicacion', models.CharField(max_length=255, verbose_name='Ubicación del Evento')),
                ('causa_probable', models.TextField(blank=True, verbose_name='Causa Probable')),
                ('fecha_ocurrencia', models.DateField(verbose_name='Fecha de Ocurrencia del Evento')),
                ('fecha_reporte', models.DateField(auto_now_add=True, verbose_name='Fecha de Reporte en Sistema')),
                ('fecha_apertura', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Apertura Oficial')),
                ('descripcion', models.TextField(verbose_name='Descripción Detallada del Siniestro')),
                ('dias_transcurridos_reporte', models.IntegerField(blank=True, editable=False, null=True, verbose_name='Días entre Ocurrencia y Reporte')),
                ('fuera_de_plazo', models.BooleanField(default=False, verbose_name='¿Reportado fuera del plazo de 15 días?')),
                ('monto_reclamado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Reclamado')),
                ('monto_aprobado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto Aprobado por Aseguradora')),
                ('deducible_aplicado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Deducible Aplicado')),
                ('monto_a_pagar', models.DecimalField(blank=True, decimal_places=2, help_text='Monto aprobado - deducible', max_digits=12, null=True, verbose_name='Monto Final a Pagar')),
                ('estado', django_fsm.FSMField(choices=[('reportado', 'Reportado'), ('docs_incompletos', 'Documentos Incompletos'), ('docs_completos', 'Documentos Completos'), ('enviado', 'Enviado a Aseguradora'), ('en_revision', 'En Revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('liquidado', 'Liquidado'), ('pagado', 'Pagado'), ('cerrado', 'Cerrado'), ('fuera_plazo', 'Fuera de Plazo')], default='reportado', max_length=50, verbose_name='Estado Actual')),
                ('cobertura_valida', models.BooleanField(default=False, verbose_name='¿Cobertura Válida?')),
                ('fecha_envio_aseguradora', models.DateField(blank=True, null=True, verbose_name='Fecha de Envío a Aseguradora')),
                ('fecha_limite_respuesta_aseguradora', models.DateField(blank=True, editable=False, null=True, verbose_name='Fecha Límite Respuesta (8 días)')),
                ('fecha_respuesta_aseguradora', models.DateField(blank=True, null=True, verbose_name='Fecha Real de Respuesta Aseguradora')),
                ('aseguradora_fuera_de_plazo', models.BooleanField(default=False, verbose_name='¿Aseguradora respondió fuera de plazo?')),
                ('fecha_limite_pago', models.DateField(blank=True, editable=False, null=True, verbose_name='Fecha Límite de Pago (72 horas)')),
                ('fecha_pago_real', models.DateField(blank=True, null=True, verbose_name='Fecha Real de Pago')),
                ('pago_fuera_de_plazo', models.BooleanField(default=False, verbose_name='¿Pago fuera de plazo?')),
                ('fecha_cierre', models.DateField(blank=True, null=True, verbose_name='Fecha de Cierre Final')),
                ('tiempo_resolucion_dias', models.IntegerField(blank=True, editable=False, null=True, verbose_name='Tiempo Total de Resolución (días)')),
                ('tipo_bien', models.CharField(max_length=100, verbose_name='Tipo de Bien Afectado')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('numero_serie', models.CharField(max_length=100, verbose_name='Número de Serie/Placa')),
                ('observaciones_internas', models.TextField(blank=True, verbose_name='Observaciones Internas')),
                ('razon_rechazo', models.TextField(blank=True, verbose_name='Razón de Rechazo')),
                ('documentos_faltantes', models.TextField(blank=True, help_text='Lista de documentos que faltan por entregar', verbose_name='Documentos Faltantes')),
                ('aseguradora_destino', models.CharField(blank=True, max_length=100, verbose_name='Aseguradora Destino')),
                ('correo_aseguradora', models.EmailField(blank=True, max_length=254, verbose_name='Correo de la Aseguradora')),
                ('mensaje_aseguradora', models.TextField(blank=True, verbose_name='Mensaje enviado a Aseguradora')),
                ('notas_liquidacion', models.TextField(blank=True, verbose_name='Notas de Liquidación')),
                ('notas_cierre', models.TextField(blank=True, verbose_name='Notas de Cierre')),
                ('asesor_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.asesorutpl', verbose_name='Asesor UTPL Asignado')),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='siniestros.broker', verbose_name='Broker Asignado')),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='siniestros', to='polizas.poliza', verbose_name='Póliza')),
                ('ramo', models.ForeignKey(help_text='El ramo que gobierna este siniestro', on_delete=django.db.models.deletion.PROTECT, related_name='siniestros', to='polizas.ramopoliza', verbose_name='Ramo Específico')),
                ('reclamante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='siniestros_reportados', to='usuarios.usuario', verbose_name='Reclamante (Usuario Sistema)')),
            ],
            options={
                'verbose_name': 'Siniestro',
                'verbose_name_plural': 'Siniestros',
                'ordering': ['-fecha_reporte'],
            },
        ),
        migrations.CreateModel(
            name='RoboSiniestro',
            fields=[
                ('siniestro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='info_robo', serialize=False, to='siniestros.siniestro')),
                ('denuncia_policial', models.TextField(blank=True, verbose_name='Número/Detalle Denuncia Policial')),
                ('fiscalia', models.CharField(blank=True, max_length=200, verbose_name='Fiscalía')),
                ('fecha_denuncia', models.DateField(blank=True, null=True, verbose_name='Fecha de Denuncia')),
            ],
            options={
                'verbose_name': 'Datos de Robo',
                'verbose_name_plural': 'Datos de Robo',
            },
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=30)),
                ('estado_nuevo', models.CharField(max_length=30)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.CharField(blank=True, max_length=150)),
                ('observaciones', models.TextField(blank=True)),
                ('siniestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='siniestros.siniestro')),
            ],
            options={
                'verbose_name': 'Historial de Estado',
                'verbose_name_plural': 'Historial de Estados',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoSiniestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('carta', 'Carta Formal'), ('informe', 'Informe Técnico'), ('denuncia', 'Denuncia Fiscalía'), ('proforma', 'Proforma de Reparación'), ('preexistencia', 'Certificado de Preexistencia'), ('salvamento', 'Salvamento'), ('finiquito', 'Finiquito'), ('comprobante_pago', 'Comprobante de Pago'), ('liquidacion', 'Liquidación Aseguradora'), ('otro', 'Otro')], max_length=30, null=True, verbose_name='Tipo de Documento')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='siniestros/documentos/%Y/%m/', verbose_name='Archivo')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Subida')),
                ('siniestro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='siniestros.siniestro')),
            ],
            options={
                'verbose_name': 'Documento de Siniestro',
                'verbose_name_plural': 'Documentos de Siniestro',
                'ordering': ['-fecha_subida'],
>>>>>>> Stashed changes
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='siniestro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siniestros.siniestro'),
        ),
    ]
