# Generated by Django 4.2.27 on 2026-01-12 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polizas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('descripcion_evento', models.CharField(max_length=255)),
                ('dias_transcurridos', models.IntegerField()),
                ('estado', models.IntegerField()),
                ('fecha_ocurrencia', models.DateField()),
                ('fecha_reporte', models.DateField()),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polizas.bienasegurado')),
            ],
        ),
        migrations.CreateModel(
            name='Danio',
            fields=[
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='siniestros.evento')),
                ('area_asignada', models.CharField(max_length=100)),
                ('tecnico_asignado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hurto',
            fields=[
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='siniestros.evento')),
                ('ubicacion_ultima_vista', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Robo',
            fields=[
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='siniestros.evento')),
                ('valor_perdido', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Siniestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cobertura_valida', models.IntegerField()),
                ('estado', models.IntegerField()),
                ('fecha_apertura', models.DateField()),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('tiempo', models.IntegerField()),
                ('asesor_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.asesorutpl')),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='siniestros.broker')),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polizas.poliza')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='siniestro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siniestros.siniestro'),
        ),
    ]
