# Generated by Django 5.2.9 on 2026-01-13 08:03

import django.db.models.deletion
import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polizas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('descripcion_evento', models.CharField(max_length=255)),
                ('dias_transcurridos', models.IntegerField()),
                ('estado', models.IntegerField()),
                ('fecha_ocurrencia', models.DateField()),
                ('fecha_reporte', models.DateField()),
                ('ubicacion', models.CharField(max_length=255)),
                ('tipo_evento', models.CharField(max_length=50)),
                ('bien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polizas.bienasegurado')),
            ],
        ),
        migrations.CreateModel(
            name='Danio',
            fields=[
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='siniestros.evento')),
                ('area_asignada', models.CharField(max_length=100)),
                ('tecnico_asignado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hurto',
            fields=[
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='siniestros.evento')),
                ('ubicacion_ultima_vista', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Robo',
            fields=[
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='siniestros.evento')),
                ('valor_perdido', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Siniestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_siniestro', models.CharField(max_length=20, unique=True, verbose_name='Número de Siniestro')),
                ('fecha_ocurrencia', models.DateField(verbose_name='Fecha de Ocurrencia')),
                ('fecha_reporte', models.DateField(auto_now_add=True, verbose_name='Fecha de Reporte')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('monto_reclamado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Reclamado')),
                ('monto_aprobado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto Aprobado')),
                ('estado', django_fsm.FSMField(choices=[('reportado', 'Reportado'), ('en_revision', 'En Revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('pagado', 'Pagado')], default='reportado', max_length=50, verbose_name='Estado')),
                ('cobertura_valida', models.IntegerField()),
                ('fecha_apertura', models.DateField()),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('tiempo', models.IntegerField()),
                ('tipo_bien', models.CharField(max_length=50)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('numero_serie', models.CharField(max_length=100)),
                ('asesor_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.asesorutpl')),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='siniestros.broker')),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siniestros', to='polizas.poliza', verbose_name='Póliza')),
                ('reclamante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siniestros', to='usuarios.usuario', verbose_name='Reclamante')),
            ],
            options={
                'verbose_name': 'Siniestro',
                'verbose_name_plural': 'Siniestros',
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='siniestro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siniestros.siniestro'),
        ),
    ]
