# Generated by Django 5.2.9 on 2026-01-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siniestros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='tipo_evento',
            field=models.CharField(default='danio', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='ubicacion',
            field=models.CharField(default='No especificado', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siniestro',
            name='marca',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='modelo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='numero_serie',
            field=models.CharField(default='SIN-SERIE', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siniestro',
            name='tipo_bien',
            field=models.CharField(default='computo', max_length=50),
            preserve_default=False,
        ),
    ]
