# Generated by Django 5.2.9 on 2026-01-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siniestros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siniestro',
            name='tiempo',
        ),
        migrations.AddField(
            model_name='siniestro',
            name='reclamante_email',
            field=models.EmailField(default='desconocido@correo.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siniestro',
            name='reclamante_nombre',
            field=models.CharField(default='Desconocido', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siniestro',
            name='reclamante_telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='tiempo_resolucion_dias',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siniestro',
            name='cobertura_valida',
            field=models.BooleanField(default=False),
        ),
    ]
