# Generated by Django 5.2.9 on 2026-01-18 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siniestros', '0002_remove_siniestro_tiempo_siniestro_reclamante_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hurto',
            name='evento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='siniestros.siniestro'),
        ),
        migrations.AlterField(
            model_name='robo',
            name='evento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='siniestros.siniestro'),
        ),
        migrations.AlterField(
            model_name='danio',
            name='evento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='siniestros.siniestro'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='causa_probable',
            field=models.TextField(blank=True, verbose_name='Causa Probable'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='deducible_aplicado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Deducible Aplicado'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='fecha_envio_aseguradora',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Envío a Aseguradora'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='fecha_respuesta_aseguradora',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Respuesta Aseguradora'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='tipo_evento',
            field=models.CharField(default='desconocido', max_length=50, verbose_name='Tipo de Evento'),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='ubicacion',
            field=models.CharField(default='No especificada', max_length=255, verbose_name='Ubicación del Evento'),
        ),
        migrations.AlterField(
            model_name='siniestro',
            name='cobertura_valida',
            field=models.BooleanField(default=False, verbose_name='Cobertura Válida'),
        ),
        migrations.AlterField(
            model_name='siniestro',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción del Siniestro'),
        ),
        migrations.AlterField(
            model_name='siniestro',
            name='fecha_apertura',
            field=models.DateField(verbose_name='Fecha de Apertura'),
        ),
        migrations.AlterField(
            model_name='siniestro',
            name='fecha_cierre',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Cierre'),
        ),
        migrations.AlterField(
            model_name='siniestro',
            name='tiempo_resolucion_dias',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tiempo de Resolución (días)'),
        ),
        migrations.CreateModel(
            name='DocumentoSiniestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('carta', 'Carta Formal'), ('informe', 'Informe Técnico'), ('denuncia', 'Denuncia Fiscalía'), ('proforma', 'Proforma'), ('preexistencia', 'Preexistencia'), ('finiquito', 'Finiquito'), ('comprobante_pago', 'Comprobante de Pago')], max_length=30)),
                ('archivo', models.FileField(upload_to='siniestros/documentos/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('siniestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='siniestros.siniestro')),
            ],
            options={
                'verbose_name': 'Documento de Siniestro',
                'verbose_name_plural': 'Documentos de Siniestro',
            },
        ),
        migrations.CreateModel(
            name='PagareSiniestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='siniestros/pagares/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Firma'), ('firmado', 'Firmado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('fecha_firma', models.DateField(blank=True, null=True)),
                ('siniestro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagare', to='siniestros.siniestro')),
            ],
            options={
                'verbose_name': 'Pagaré',
                'verbose_name_plural': 'Pagarés',
            },
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
    ]
