# Generated by Django 5.1.4 on 2026-01-12 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0001_initial'),
        ('siniestros', '0002_evento_tipo_evento_evento_ubicacion_siniestro_marca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='bien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polizas.bienasegurado'),
        ),
    ]
