# Generated by Django 5.2.9 on 2026-01-12 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0001_initial'),
        ('siniestros', '0003_alter_evento_bien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siniestro',
            name='poliza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polizas.poliza'),
        ),
    ]
