# Generated by Django 5.2.9 on 2026-01-25 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notificaciones', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Notificación', 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.AddField(
            model_name='notificacion',
            name='categoria',
            field=models.CharField(choices=[('poliza_vencer', 'Póliza por Vencer'), ('siniestro_docs', 'Documentos Incompletos'), ('siniestro_plazo', 'Siniestro Fuera de Plazo'), ('aseguradora_plazo', 'Aseguradora Fuera de Plazo'), ('pago_pendiente', 'Pago Pendiente'), ('general', 'General')], default='general', max_length=30),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='usuarios.asesorutpl'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_actividad', models.CharField(choices=[('siniestro_creado', 'Siniestro Creado'), ('siniestro_actualizado', 'Siniestro Actualizado'), ('documento_subido', 'Documento Subido'), ('estado_cambiado', 'Estado Cambiado'), ('poliza_creada', 'Póliza Creada'), ('poliza_actualizada', 'Póliza Actualizada'), ('notificacion_enviada', 'Notificación Enviada')], max_length=30)),
                ('descripcion', models.CharField(max_length=255)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.asesorutpl')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
