# Generated by Django 5.2.9 on 2026-01-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_alter_notificacion_options_notificacion_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='correo_enviado',
            field=models.BooleanField(default=False, verbose_name='Correo Enviado'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='fecha_envio_correo',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='veces_enviado',
            field=models.IntegerField(default=0, verbose_name='Veces Enviado'),
        ),
    ]
