# Generated by Django 5.2.9 on 2026-01-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0003_notificacion_correo_enviado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='categoria',
            field=models.CharField(choices=[('poliza_vencer', 'Póliza por Vencer'), ('siniestro_docs', 'Documentos Incompletos'), ('siniestro_plazo', 'Siniestro Fuera de Plazo'), ('aseguradora_plazo', 'Aseguradora Fuera de Plazo'), ('pago_pendiente', 'Pago Pendiente')], default='siniestro_docs', max_length=30),
        ),
    ]
