# Generated by Django 4.2.27 on 2026-01-12 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BienAsegurado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('estado', models.IntegerField()),
                ('tipo_bien', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aseguradora', models.CharField(max_length=100)),
                ('cobertura', models.CharField(max_length=255)),
                ('estado', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('prima', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polizas.bienasegurado')),
            ],
        ),
        migrations.AddField(
            model_name='bienasegurado',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polizas.zona'),
        ),
        migrations.CreateModel(
            name='ResponsableBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polizas.bienasegurado')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.personaresponsable')),
            ],
            options={
                'unique_together': {('responsable', 'bien')},
            },
        ),
    ]
