# Generated by Django 5.2.9 on 2026-01-13 08:03

import django.db.models.deletion
import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BienAsegurado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('estado', models.IntegerField()),
                ('tipo_bien', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_poliza', models.CharField(max_length=20, unique=True, verbose_name='Número de Póliza')),
                ('tipo_poliza', models.CharField(max_length=50, verbose_name='Tipo de Póliza')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de Emisión')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('prima', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prima')),
                ('cobertura', models.TextField(verbose_name='Cobertura')),
                ('estado', django_fsm.FSMField(choices=[('activa', 'Activa'), ('suspendida', 'Suspendida'), ('cancelada', 'Cancelada'), ('expirada', 'Expirada')], default='activa', max_length=50, verbose_name='Estado')),
                ('aseguradora', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polizas.bienasegurado')),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polizas', to='usuarios.usuario', verbose_name='Titular')),
            ],
            options={
                'verbose_name': 'Póliza',
                'verbose_name_plural': 'Pólizas',
            },
        ),
        migrations.AddField(
            model_name='bienasegurado',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polizas.zona'),
        ),
        migrations.CreateModel(
            name='ResponsableBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polizas.bienasegurado')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.personaresponsable')),
            ],
            options={
                'unique_together': {('responsable', 'bien')},
            },
        ),
    ]
