# Generated by Django 5.2.9 on 2026-01-18 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RamoPoliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=100)),
                ('subgrupo', models.CharField(max_length=100)),
                ('ramo', models.CharField(max_length=100)),
                ('suma_asegurada', models.DecimalField(decimal_places=2, max_digits=14)),
                ('prima', models.DecimalField(decimal_places=2, max_digits=12)),
                ('base_imponible', models.DecimalField(decimal_places=2, max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_facturado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deducible_minimo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deducible_porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ramos', to='polizas.poliza')),
            ],
        ),
    ]
