# Generated by Django 5.2.9 on 2026-01-19 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0002_ramopoliza'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='polizas_pdf/'),
        ),
        migrations.CreateModel(
            name='Deducible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deducibles', to='polizas.poliza')),
            ],
            options={
                'verbose_name': 'Deducible',
                'verbose_name_plural': 'Deducibles',
            },
        ),
    ]
