# Generated by Django 5.2.9 on 2026-01-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0003_deducible'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='polizas_pdf/'),
        ),
    ]
