# Generated by Django 5.2.9 on 2026-01-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_reporte_siniestro', models.IntegerField(default=15, verbose_name='Días máx para reportar')),
                ('dias_respuesta_seguro', models.IntegerField(default=3, verbose_name='Días meta respuesta')),
                ('dias_pago', models.IntegerField(default=30, verbose_name='Días máx para pago')),
                ('descuento_pronto_pago', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('plazo_max_descuento', models.IntegerField(default=10)),
                ('alerta_fuera_plazo', models.BooleanField(default=True)),
                ('alerta_pagos_vencidos', models.BooleanField(default=True)),
                ('alerta_doc_incompleta', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ReglaDeducible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_poliza', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=150)),
                ('minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
