# Generated by Django 6.0.1 on 2026-01-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deducible_auto_min', models.DecimalField(decimal_places=2, default=200.0, max_digits=10)),
                ('deducible_auto_max', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('dias_reporte_siniestro', models.IntegerField(default=15, verbose_name='Días máx para reportar')),
                ('dias_respuesta_seguro', models.IntegerField(default=3, verbose_name='Días meta respuesta')),
                ('dias_pago', models.IntegerField(default=30, verbose_name='Días máx para pago')),
                ('alerta_fuera_plazo', models.BooleanField(default=True)),
                ('alerta_pagos_vencidos', models.BooleanField(default=True)),
                ('alerta_doc_incompleta', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Parámetro del Sistema',
                'verbose_name_plural': 'Parámetros del Sistema',
            },
        ),
    ]
