# Generated by Django 6.0.1 on 2026-01-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaDeducible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_poliza', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=150)),
                ('minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='parametrosistema',
            options={},
        ),
        migrations.RemoveField(
            model_name='parametrosistema',
            name='deducible_auto_max',
        ),
        migrations.RemoveField(
            model_name='parametrosistema',
            name='deducible_auto_min',
        ),
        migrations.AddField(
            model_name='parametrosistema',
            name='descuento_pronto_pago',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='parametrosistema',
            name='plazo_max_descuento',
            field=models.IntegerField(default=10),
        ),
    ]
