# Generated by Django 4.2.27 on 2026-01-12 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polizas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=100)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('obligatorio', models.BooleanField()),
                ('ruta_archivo', models.CharField(max_length=255)),
                ('tipo_doc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('tipo_notificacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('tipo_reporte', models.CharField(max_length=50)),
                ('bien', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polizas.bienasegurado')),
                ('gerente_autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.gerente')),
            ],
        ),
    ]
