# Generated by Django 4.2.27 on 2026-01-12 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('siniestros', '0001_initial'),
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='siniestro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='siniestros.siniestro'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='siniestro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siniestros.siniestro'),
        ),
        migrations.AddField(
            model_name='documento',
            name='siniestro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siniestros.siniestro'),
        ),
    ]
